### ISSUE TITLE
Windows support?

### ISSUE THREAD

**Issue by szkrd** [WebReflection/polpetta#1]
The module installs on Windows, but the generated cmd file has hardcoded "/usr/local" - though this may be a node corruption; nevertheless if I start the module without parameters it shows a polpetta folder (in the browser) which, when clicked, on shows the raw polpetta source (it is not executed).

Also note that if I start the module with a "." parameter it does not resolve the current path; if I start it with a port only, it still thinks it is a directory - some flexibility with the parameters would be nice. Thanks!

**Comment by WebReflection** [comment]
there's no cmd file and that is a common *nix directive ... sorry, windows does not support that directive but I might create a .bat file able to launch polpetta through node automagically for windows. Polpetta creates the server, so if it's in its own folder it's normal that is showed since is not a .njs file but just a file as any other is showed. Only .njs files are served as node modules, all others are served as they are, html as html, txt as text, png as image, etc etc ... folders are listed: not an issue but actually exactly what you get here. I will try the "." while the port as unique parameter should be already supported, weird is not, I'll check though. In any case, the dot is not necessary, since it's the default, the port not working could be. I close this since there is one possible issue out of 4 listed. Thanks for the report in any case, cheers.

**Comment by szkrd** [comment]
There is a cmd file which is generated by node (most of the time stored in "c:\Users\username\AppData\Roaming\npm\polpetta.cmd") and the cmd extension is the same as the "bat" one (at least on nt-like systems).

The file path was neccessary, without that polpetta did not launch in the current directory, but in its very own build directory, but I do think this may be a problem with the launcher itself:

```
c:\Users\szkurdi\Downloads>polpetta
http://127.0.0.1:1337/
# (?) polpetta v0.1.0 C:\Users\szkurdi\AppData\Roaming\npm\node_modules\polpetta\build
```

As you stated I tried to add an index.njs to an empty directory, but this was the output (and the server died):

```
c:\Users\szkurdi\Downloads>polpetta c:\Users\szkurdi\Downloads
http://127.0.0.1:1337/
# (?) polpetta v0.1.0 c:\Users\szkurdi\Downloads
hello

C:\Users\szkurdi\AppData\Roaming\npm\node_modules\polpetta\build\polpetta:636
  module.onload.call(
                ^
TypeError: Cannot call method 'call' of undefined
    at requireNJS (C:\Users\szkurdi\AppData\Roaming\npm\node_modules\polpetta\build\polpetta:636:17)
    at Array.fileStats (C:\Users\szkurdi\AppData\Roaming\npm\node_modules\polpetta\build\polpetta:156:9)
    at Object.oncomplete (fs.js:297:15)
```

My node version is 0.8.1, I'm on Windows 7; thank you!

**Comment by WebReflection** [comment]
to use an .njs file you need to export the unload function 

```
// your index.njs file
this.onload = function (req, res) {
   // here you do whatever you want with node
   // if you want to use polpetta facilities ...
   this.output.push("Hello World!");
   this.flush();
};
```

There are few examples in the test folder, look at that index.njs, postings, cookie.njs, or file.njs to have full coverage of polpetta usage :)

**Comment by szkrd** [comment]
You're right indeed, I just added a plain console.log, sorry!

**Comment by WebReflection** [comment]
I have just verified in Windows ( something I have never done so I am actually surprised it worked out of the box ) the folder as "", ".", or ".\" is behaving as expected, it launches from the folder where the polpetta file is ... **not the polpetta folder** but **the build/polpetta**

The npm automatic file looks problematic indeed ... I need to investigate about specifying different path for the cmd in Windows while the port problem is gonna be fixed ASAP!

**Comment by WebReflection** [comment]
I have just pushed the v0.1.1 which fixes all paths and ports problem you had ... now the current folder is the default, the dot should work as expected, and the port as single argument should do the trick too.

Please let me know if you still have those problems while I am looking at the .cmd problem as I write ;)

**Comment by szkrd** [comment]
All issues fixed, nice work! Thanks!

**Comment by WebReflection** [comment]
for the record ... v0.1.2 now works .. `npm update polpetta` and the .cmd file will just launch polpetta ... the folder, through double click, gonna be the bin one in any case thought but there's not much I can do there.

thanks for testing, polpetta now is ready for Windows users :)
