### ISSUE TITLE
diff

### ISSUE THREAD

**Issue by geddski** [WebReflection/polpetta#3]
Promise I'm not trolling. Just wanted to know the difference between this and [http-server](https://github.com/nodeapps/http-server)? Thx.

**Comment by WebReflection** [comment]
that looks like [serverdir](https://github.com/remy/servedir) and I had same question already so maybe I should specify this directly on the home of this project. First of all, both serverdir and http-server looks more like

```
python -m SimpleHTTPServer
```

and this is what polpetta does as well **except** polpetta does even more: it brings the possibility to configure responses, as example through _.htaccess_ file and the ability to intercept calls and flush differently ( .md files served as HTML, as example ) and most important, it lets you quick prototype node.js modules.

Every **.njs** file will be served as node module through a _this.onload = function (req, res, polpetta) {};_ method where polpetta will bring **get**, **post**, **cookie**, and **file** with the same simplicity PHP does.

As summary, **polpetta is able to serve dynamic content** while any other solution is not.

Does this clarify the aim of this project? :)

**Comment by WebReflection** [comment]
and for _while any other solution is not._ I measn any other **static content based solution** ;)

**Comment by WebReflection** [comment]
this comes from JavaScript weekly and I believe is the best summary ever :D
"_Runs up a Node-powered HTTP server in any folder you want whereupon '.njs' files get executed CGI-style._"

that's the difference ;)

**Comment by geddski** [comment]
got it. thanks for the thorough response, I'll have to try this out.
