### ISSUE TITLE
Unable to reach server from outside virtual machine

### ISSUE THREAD

**Issue by ottonascarella** [WebReflection/polpetta#5]
Hi there,

Thanks for polpetta.
I love the name!

I have a virtual machine (Linux) running polpetta.
When I run it, It works perfectly within the machine, but if I try to reach it from the host machine (Windows 7), it does not find it.

**Comment by WebReflection** [comment]
can you ping that machine from the Windows 7 host ? can you ping the polpetta port too ? is there any firewall in the middle ?

**Comment by ottonascarella** [comment]
I can. I have also an apache2 server running on it, and it works.

On 28 December 2012 15:36, Andrea Giammarchi notifications@github.comwrote:

> can you ping that machine from the Windows 7 host ? can you ping the
> polpetta port too ? is there any firewall in the middle ?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/WebReflection/polpetta/issues/5#issuecomment-11736826.

## 

Otto

**Comment by WebReflection** [comment]
is really hard to be able to understand and replace your situation ... by any chance you can tell me more? Have you tried to use a different port with polpetta? and what port are you using now?

**Comment by ottonascarella** [comment]
I tried to use other ports, yes.

I have a Windows 7 host, and a Ubuntu 12.04 server (guest) running on the
vmware player.

I had a similar problem with weinre: it usually binds the connection to
localhost. However, when I try to reach it from outside the machine, I have
to use the IP of the machine in the network, and it fails. The only way out
is to do weinre --boundHost "THE IP OF THE MACHINE", that way it works.

servedir app works fine on the same set up though, but does not server njs
files.

On 28 December 2012 22:53, Andrea Giammarchi notifications@github.comwrote:

> is really hard to be able to understand and replace your situation ... by
> any chance you can tell me more? Have you tried to use a different port
> with polpetta? and what port are you using now?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/WebReflection/polpetta/issues/5#issuecomment-11745475.

## 

Otto

**Comment by ottonascarella** [comment]
I have just ran a test using your servedir, python -m SimpleHTTPServer and
polpetta.

When I see the type of connection polpetta opens, it's described as
http-proxy, whereas both the other 2 apps are described as http-alt by nmap.

that may be another clue.

On 28 December 2012 23:08, Otto Nascarella ottoln@gmail.com wrote:

> I tried to use other ports, yes.
> 
> I have a Windows 7 host, and a Ubuntu 12.04 server (guest) running on the
> vmware player.
> 
> I had a similar problem with weinre: it usually binds the connection to
> localhost. However, when I try to reach it from outside the machine, I have
> to use the IP of the machine in the network, and it fails. The only way out
> is to do weinre --boundHost "THE IP OF THE MACHINE", that way it works.
> 
> servedir app works fine on the same set up though, but does not server njs
> files.
> 
> On 28 December 2012 22:53, Andrea Giammarchi notifications@github.comwrote:
> 
> > is really hard to be able to understand and replace your situation ... by
> > any chance you can tell me more? Have you tried to use a different port
> > with polpetta? and what port are you using now?
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/WebReflection/polpetta/issues/5#issuecomment-11745475.
> 
> ## 
> 
> Otto

## 

Otto

**Comment by WebReflection** [comment]
hey, I had to change the default host port forcing `0.0.0.0` instead of `127.0.0.1` and this is because the latter one is local only in non windows machine. Maybe that was the problem in your case too? Can you please let me know if that work? Either update to latest one or force the HOST constant on top of the file to `0.0.0.0`, thanks!

**Comment by ottonascarella** [comment]
Hi Andrea,

Now it works if bound to 0.0.0.0.
It did not use to work before on that configuration, so you know...

thanks for the fix.

Otto

On 10 February 2013 21:24, Andrea Giammarchi notifications@github.comwrote:

> hey, I had to change the default host port forcing 0.0.0.0 instead of
> 127.0.0.1 and this is because the latter one is local only in non windows
> machine. Maybe that was the problem in your case too? Can you please let me
> know if that work? Either update to latest one or force the HOST constant
> on top of the file to 0.0.0.0, thanks!
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/WebReflection/polpetta/issues/5#issuecomment-13363859..

## 

Otto
